### PR TITLE
Authentication with session token

### PR DESCRIPTION
**Pull request by isocolsky**

### CODE REVIEW

**Comment by braydonf** [comment]
What's the motivation for this?

**Comment by isocolsky** [comment]
The idea is to provide a more lightweight mechanism to interact with the wallet service that doesn't require signing/verifying each request. Some endpoints like `/notifications` are very bussy and could benefit a lot from this. Do you see any downside to having this in place?

**Comment by braydonf** [comment]
We could switch to use optimized c code for verifying, there should be huge improvements with performance. Here is a branch that switches verifying to use secp256k1 https://github.com/braydonf/bitcore-wallet-service/commit/20cc273a6f3e555e7cd7f2be125bc5f6a00e97cd

**Comment by isocolsky** [comment]
rebased

**Pull request merged**
