### PR TITLE
Allow arbitrary metadata for tx proposals

### PR DESCRIPTION
**Pull request by troggy**
This way Copay addons may attach related data to proposals

### CODE REVIEW

**Comment by isocolsky** [comment]
Please, add a line to the `#createTx` -> `should create a tx` test making sure the metadata field is correctly retrieved.

**Comment by isocolsky** [comment]
One more small comment: do you think `metadata` is an appropriate name for this field? I would think metadata refers to data about the txp object itself and would be handled by BWS. Since this is something provided by the user, maybe a better name would be `customData`?

**Comment by troggy** [comment]
@isocolsky Yes, ``customData`` is better. Thanks!

**Comment by troggy** [comment]
Please review

**Comment by troggy** [comment]
Rebased

**Comment by matiu** [comment]
LGTM. One question, Are we  OK that `customData` is not protected by any copayer signature? It could be tampered by a compromised BWS.

**Comment by troggy** [comment]
Good question. For colored coins we don't use ``customData`` for anything sensitive, it's only used for presentational purposes (e.g. show color information for pending proposals). Do you think it still worth signing?

**Pull request merged**
