### PR TITLE
Allow change address in createTx to be specified.

### PR DESCRIPTION
**Pull request by hectorchu**
I need this for a protocol where the change address is set to an existing address.

### CODE REVIEW

**Comment by matiu** [comment]
Could you explain more the use case for this? It seems that reusing an address (for chance) will always be a bad idea.

Besides that, changeAddress should be a `Address` instance. It should include many attributes so clients can verify the address belongs to the wallet.

**Comment by hectorchu** [comment]
I'm trying to create a transaction with two outputs. One output is an address I specify, and I want the other output to pay to an existing address in the wallet. I don't want any change outputs.

It seems to me that the easiest way to accomplish this (and I have tried it with this PR and it works) is to simply set the change address to the existing address in the wallet. Then creating a transaction with only one output paying to the address I specify, will automatically result in a two output transaction with the outputs the way I want them.

My code calls getMainAddresses on the wallet, selects one of the addresses from the array, and then passes it to createTx in the changeAddress option. So I believe it is an Address instance.

**Comment by hectorchu** [comment]
Is there any comment on my use case? Is it something that bitcore-wallet-service will ever support?

Another consideration is that the diff I am proposing is very trivial. Is there any reason why the diff can't be applied as is?

**Comment by tomtruitt** [comment]
I'm also looking for this.  reusing an address is not the goal but to specify where change goes

**Comment by tomtruitt** [comment]
Essentially dispersing funds to two addresses using only one transaction

**Comment by tomtruitt** [comment]
If each address could be a newly generated HD address then even better

**Comment by isocolsky** [comment]
> Essentially dispersing funds to two addresses using only one transaction

Could you please elaborate on this use case?

**Comment by tomtruitt** [comment]
Yes I may not be thinking about this correctly. But essentially I want to take funds accepted at one  address send a portion to myself and the remainder  to my partner.

**Comment by tomtruitt** [comment]
Or initially receive funds in that way from just one transaction.

**Comment by dabura667** [comment]
> a portion to myself and the remainder to my partner.

You just described exactly what change addresses are.

Do you mean "a portion to **my other, non-Copay wallet** and the remainder to my partner."?

**Comment by isocolsky** [comment]
If I understand correctly, this use case would be better addressed by having the possibility of deducting fees from the amount to be sent instead of the change amount. So let's say you receive 1.5BTC and you would like to keep 1 BTC and send the remaining (0.5 - fee) to your partner. You would type 0.5 in the "to amount" and check the "receiver pays for fees". Would something like this be what you need?

**Comment by isocolsky** [comment]
Seeing @dabura667 comment, this may not be about fees after all. If you are looking to distribute funds on several destination wallets (other than the source wallet be them Copay or non-Copay wallets) in a single transaction, the correct way of doing this would be to use multiple-outputs. This is not currently supported in Copay. Also doing this manually is a bit awkward since fees are not known until the tx is built so maybe there is still a need for an improvement.

**Comment by tomtruitt** [comment]
I'm sorry maybe I'm conflating change address with  unspent output address.

My partner and I will have separate wallets naturally so the idea is that we each get a portion of the funds received

**Comment by isocolsky** [comment]
An ideal scenario for you would be to share a 2-of-2 wallet with your partner and get paid to this wallet. From there, you would build a single tx with one output sending a portion of the funds to your separate 1-of-1 wallet and the remainder to your partner's 1-of-1 wallet. So all funds distribution would be with the approval of all parties involved. Is this correct?

**Comment by tomtruitt** [comment]
you would think but actually no... i set the agreed upon distribution and my partner in any transaction (who this is will vary based on transaction) is well aware of the terms but they aren't to have the ability to do anything for example approve or deny. they really just get a payout for the amount we agree on beforehand.

**Comment by tomtruitt** [comment]
actually yes this is about fees, just saw your earlier comment

**Comment by tomtruitt** [comment]
lol yes to put plainly i need to take a fee for myself then pass the rest on... this doesn't need to be with copay could it be done with bitcore-wallet-service/client?

**Comment by isocolsky** [comment]
Closing in favor of #513

**Pull request closed without merging**
