### PR TITLE
use the node.js default cipher suite for setting up a tls server inst…

### PR DESCRIPTION
**Pull request by gabegattis**
…ead of specifying our own

### CODE REVIEW

**Comment by matiu** [comment]
What you think about is article
https://certsimple.com/blog/a-plus-node-js-ssl
?

The default cipher suite seems to include RC4 which is insecure (note sure is that is still true for node 4)

**Comment by braydonf** [comment]
Defaults in various Node.js versions:
v0.10: https://nodejs.org/docs/latest-v0.10.x/api/tls.html (includes RC4)
v4: https://nodejs.org/dist/latest-v4.x/docs/api/tls.html#tls_modifying_the_default_tls_cipher_suite
v6: https://nodejs.org/api/tls.html#tls_modifying_the_default_tls_cipher_suite

**Comment by gabegattis** [comment]
I think using the node defaults is a good way to go, but if older versions of node are not using secure defaults, things do get tricky.

There is the option of detecting if BWS is being run with an old version of node, and then restricting the cyphersuites to not use rc4.

There is also the option of taking the position that if you want to be secure, you should be on newer versions of node.js anyway.

Another option is to use a custom, but very carefully selected, configuration and use it regardless of node version. If your node version does not support our custom config, it will break and you will have to fix it yourself. (or update your nodejs version)

As far as different node versions go, see https://github.com/nodejs/LTS#lts_schedule. 0.10 will no longer be supported after October of this year.

At the very least, we should start using defaults now. IMO, this PR will make an immediate improvement to our security. If we want to go beyond simply using defaults, we can have that discussion separate from this PR. I don't want to delay this improvement just because we haven't made a decision on how to handle it long term.

BTW, what nodejs version are we running on the production bws servers?

**Comment by matiu** [comment]
We have upgrade productions servers to node 4.4.3, so the defaults looks good https://nodejs.org/dist/latest-v4.x/docs/api/tls.html#tls_modifying_the_default_tls_cipher_suite

thanks @gabegattis and @braydonf !

**Pull request merged**
