### PR TITLE
Dynamic fee levels

### PR DESCRIPTION
**Pull request by isocolsky**

### CODE REVIEW

**Comment by matiu** [comment]
Codes looks great,great work!

Can we put the 'priority point' with 1 block?

**Comment by isocolsky** [comment]
Thanks. Yes it is possible, 2 is recommended as most of the time there is no fee high enough to guarantee with enough certainty (85%) that the tx will be included in the next block. When this happens, bitcoind returns -1. [Source](https://bitcoin.org/en/release/v0.11.0#fee-estimation-changes)

**Comment by isocolsky** [comment]
ready for review

**Comment by matiu** [comment]
great job! really looking forward for this!

**Pull request merged**
