### PR TITLE
Added app.js to spawn service scripts, PM2 compatibility

### PR DESCRIPTION
**Pull request by huangbong**
Issue: https://github.com/bitpay/bitcore-wallet-service/issues/597

Start app with PM2:

```
pm2 start app.js --name "bitcoin-wallet-service"
````

### CODE REVIEW

**Comment by martindale** [comment]
:100:!  Yes please!  You might also be interested in [running Insight using PM2](https://github.com/bitpay/insight-ui/wiki/Running-Insight-in-Production), something I tried to do before this repo existed.  Exciting to see someone else doing the same thing here!

May I suggest renaming it to `bws.js` or something non-generic, so PM2 automatically displays a correct name?  This will reduce confusion with other processes managed by the same instance.

**Comment by jadhavajay** [comment]
Is there anything pending with this PR in order to merge into master? Renaming `app.js` to `bws.js` ?

**Comment by jadhavajay** [comment]
as stated by @huangbong, we can use `--name` option of PM2. 

e.g. 
`pm2 start app.js --name "bitcoin-wallet-service"`

**Comment by matiu** [comment]
Sorry the delay, thanks for the contribution!

**Comment by matiu** [comment]
I added some related doc on the readme.

**Pull request merged**
